### ISSUE TITLE
HTML View

### ISSUE THREAD

**Issue by ahmadnassri** [ahmadnassri/app-restconsole#13]
it would be great if when the response body is html that you could have the option to render the view, rather than syntax highlighting. Reason being that when the server throws an unexpected error the message returned is harder to understand, and we don't erally care abou the code just the message.

**Comment by phpwalter** [comment]
It would be nice if RESPONSE BODY had 2 TABS on it:
- RAW View
- RENDERED View

It would default to RAW View and than I could switch to rendered if I choose.

But this means that RENDER needs to PRETTY print XML and JSON! ;)

**Comment by ahmadnassri** [comment]
agreed. I'm even thinking of 3 tabs:
RAW, RENDERED, and Pretty (should come up with good name for it)

where RAW is the response as is.
RENDERED is a rendered view ex: HTML, Images, etc ...
PRETTY would be the syntax highlighted view of the HTML/XML/JSON/etc ...

**Comment by phpwalter** [comment]
oh, much better. thank you

**Comment by croach** [comment]
Definitely agree with this suggestion. I develop in Django and being able to see the rendered HTML is so helpful when an error occurs. This is the one feature that keeps me going back to REST Client for Firefox. I really hope you can add this feature. 

Thanks a bunch for all your work.

**Comment by ahmadnassri** [comment]
thanks for the feedback @croach ... new release coming very soon that will have this.

**Comment by croach** [comment]
Excellent! Really looking forward to the new release. Thanks.
