### ISSUE TITLE
Allow for Cookies to be set

### ISSUE THREAD

**Issue by JessieAMorris** [ahmadnassri/app-restconsole#16]
I cannot find an (easy) method to set custom cookies. A set up similar to the form values fields would be nice, where a key and a value are submitted and the correct string is placed in the headers.

**Comment by ahmadnassri** [comment]
agreed, I don't use cookies that much, but this is definitely needed. how could I have missed it!

thanks, will add to next release.

**Comment by ahmadnassri** [comment]
It turns out the "Cookie" header is forbidden to set in an XMLHTTPRequest according to the specs: http://www.w3.org/TR/XMLHttpRequest/

so I cannot add this to the Chrome extension, but I will add this feature to the hosted version of REST Console ...

**Comment by JessieAMorris** [comment]
Awesome, thanks for looking into that. It's a shame that the Cookie is forbidden in the specs.
