### ISSUE TITLE
Implement XML and JSON formatter

### ISSUE THREAD

**Issue by CarlLee** [ahmadnassri/app-restconsole#19]
Please implement XML and JSON formatter, this will make your tool more useful

**Comment by ahmadnassri** [comment]
if by formatting you mean syntax highlighting then that's already implemented, as well as text formatting (spacing, line breaks etc ...) but it depends on the response content type header, it could be that you are not receiving a proper response header, or that I've not included all the possible headers for XML/JSON ...

can you tell me what the response headers are that you are receiving? along with a screenshot of the response body if possible.

thanks.

**Comment by CarlLee** [comment]
Thank you, I've found my problem, my response Content-Type is text/html instead of application/json

**Comment by ahmadnassri** [comment]
great :)
