### ISSUE TITLE
UI suggestions...

### ISSUE THREAD

**Issue by phpwalter** [ahmadnassri/app-restconsole#20]
not an issue, but UI suggestion.

Can the scroll bar be a bit more prominent? They are a bit subtle.

The "forms" for each section of this great extension takes up quite a bit of space about the RESPONSE. I'm not sure the repeating of the section titles on the right side server a real purpose. takes up a lot of real-estate.

It would make the right panel much easier to read of these section title were removed and the user was to simply  use the left panel for navigation.

Just my 2 cents on a great app.

Thank you

**Comment by ahmadnassri** [comment]
agreed, I'm doing a complete UI revamp to save up on space and use it more efficiently.

**Comment by phpwalter** [comment]
ok, thanks

**Comment by ahmadnassri** [comment]
new interface is now in github, will compile and release a new version once all the bugs have been cleared, in the meantime, feel free to download from github and and play with the new interface.
