### ISSUE TITLE
Can not set Referer header in "Custom headers"

### ISSUE THREAD

**Issue by art-shen** [ahmadnassri/app-restconsole#23]
subject

**Comment by ahmadnassri** [comment]
I believe this is a limitation in the Chrome SDK, just as we cannot set the User-Agent string ... 

HOWEVER!
I'm working on a solution.

**Comment by a-krivolapov-parc** [comment]
I don't know about extensions, but Chrome applications can set Referer header.
Seen in the Advanced Rest Client Application.

**Comment by ahmadnassri** [comment]
I'll double check ..

**Comment by ahmadnassri** [comment]
I just confirmed, the Referer header CANNOT be set according to W3C specification (http://www.w3.org/TR/XMLHttpRequest/#the-setrequestheader-method)

even in the application you mentioned, it is not allowed.

however, I have a SaaS based version of REST Console coming soon, that will allow you to set all the headers as it proxies all the requests through a server for maximum customization.
