### ISSUE TITLE
Incorrect variables encoding in application/x-www-form-urlencoded POST request.

### ISSUE THREAD

**Issue by art-shen** [ahmadnassri/app-restconsole#24]
**Example:**
Амаль

**Result:**
\u0410\u043c\u0430\u043b\u044c

**Expected:**
%D0%90%D0%BC%D0%B0%D0%BB%D1%8C

need to urlencode

**Comment by ahmadnassri** [comment]
interesting, I may need your help to further test this on the next release ..

**Comment by a-krivolapov-parc** [comment]
Ok, I'll be glad to help
