### ISSUE TITLE
URL without protocol is not valid

### ISSUE THREAD

**Issue by art-shen** [ahmadnassri/app-restconsole#26]
An error that the URL is not valid when trying to send a request to "example.com".
May be better to just automatically add the "http://" if protocol is not specified in the url.

**Comment by ahmadnassri** [comment]
agreed.

**Comment by ahmadnassri** [comment]
here's an interesting related question ...

what other uri schmes are valid in JavaScript / XMLHTTPRequest ... ?

just wondering if its just http/https ... (thinking out loud)

**Comment by ahmadnassri** [comment]
according to a quick google search, XMLHTTPRequest only supports http/https ... I could be wrong but for now I'm limiting it to those two.
