### ISSUE TITLE
User interface feedback

### ISSUE THREAD

**Issue by art-shen** [ahmadnassri/app-restconsole#29]
Change the theme for the syntax highlighting is a very cool feature.
But we have to always scroll up and down, to see how the theme looks.
Perhaps the choice of theme for syntax highlighting should be near query result.
The option "Hide line numbers" then could be moved down too. With these changes Options part would be much smaller =)

Overall a very nice interface, but the Request part takes up much space in height. You have to scroll very often. It might be worth grouping query options to tabs as it is done with Response (Response Body, Response Headers ...). If we could all put everything on one screen, so just do entirely without scrolling, then I think it would be very cool.

**Comment by ahmadnassri** [comment]
hiding the interface was an issue before in previous versions, some people didn't like it, some did ...

with this redesign, its possible to do both, I'll add an option that allows you to toggle between both views ...

**Comment by ibips** [comment]
I second the motion about having to scroll the page in this version. It would be awesome to have both choice of "tabbed"(sectional) view like v.3 and the all in the page.
