### ISSUE TITLE
Support Referer header

### ISSUE THREAD

**Issue by antelle** [ahmadnassri/app-restconsole#33]
Currently Referer header is not supported.
This makes this extension totally useless for some websites.
If this header is added as a custom one, it's omitted.

And yeah, I understand that it's not too easy, to add it because of security limitations.

**Comment by ahmadnassri** [comment]
unfortunately, its not a question of easy or not, its impossible to send the header in a JavaScript application, according to the [W3C spec](http://www.w3.org/TR/XMLHttpRequest/) so unless they come up with a new spec that Chrome implements, or for Chrome to provide a special Request API, there is nothing we can do.

that said, we are working on a proxy service that will open up a lot of possibilities including sending such forbidden headers.

but that will only work for public URLs and not local development ones.

there is no magic bullet.
