### ISSUE TITLE
Absolute positioning of autocomplete suggestion

### ISSUE THREAD

**Issue by elbowich** [ahmadnassri/app-restconsole#34]
Hiding help lines results in dropdown select of request method being misplaced.

**Comment by ahmadnassri** [comment]
sorry about that, should have tested more thoroughly, I just noticed it this morning too.

will release a new build with this fix and a few small others later today.

thanks.

**Comment by ibips** [comment]
In oAuth dialog box, when you focus the Version field, the autocomplete appear in the middle of the dialog box. This maybe related to this absolute positioning issue.

**Comment by ahmadnassri** [comment]
@ibips yes it is, I've implemented a fix, should be on the web store before the end of day.
