### ISSUE TITLE
On multiple OAuth 1.0 requests, nonce & timestamp are reused

### ISSUE THREAD

**Issue by WanaByte** [ahmadnassri/app-restconsole#35]
In version 4.0.1, when signing a request with OAuth, the same nonce is reused for each request. 

The nonce and timestamp are used for every request, unless the user specifically pops open the "oAuth" dialog box and clicks "insert". This makes it difficult to perform multiple requests in succession. Please enable a checkbox to allow for automatic timestamp and nonce generation, or an "update nonce" button that does not require the user to open the dialog box and click "Insert"

**Comment by ahmadnassri** [comment]
good point, I will add that for sure in the next release today.
