### ISSUE TITLE
Request Payload parameters are gone in request.

### ISSUE THREAD

**Issue by evertharmeling** [ahmadnassri/app-restconsole#43]
When I'm using the 'Request Payload parameters' they aren't available in my request to my API.

When performing a POST, my $_POST is totally empty? Also tried the RAW Body Request Payload that gives the same result. Custom Headers are working all right though. 
I tried the exact same request with Rest Console 3.0.7 and that's working properly. 

I'm using Chrome Rest Console 4.0.2 (the latest version)

Nevertheless great work on the new version!

**Comment by ilbalta** [comment]
Same here, latest version 4.0.1 under Ubuntu 10.10 seems unable to properly make a post request, my $_POST is always empty!

Here's an example, this is the request as seen in the "Request Body":
"
Request Url: http://www.mytesturl.com/login.php
Request Method: POST
Status Code: 200
Params: {
    "pwd": "pwd",
    "user": "user"
}
"

On login.php the only thing I do is a var dump of $_POST and results say it's an empty array.

Please get this fixed soon!!

**Comment by WanaByte** [comment]
I'm also having this problem. A workaround is to check the box for "Raw Payload" and leave it empty, and add the query parameters in the key:value pair input boxes under "Request Parameters" This seems to add the query string back in.

**Comment by ilbalta** [comment]
The trick is not working for me, maybe I got it wrong.
I am doing:
RequestPayload

> RAW Body : checked and left empy
> Request Parameters : used normally

Still nothing is received :(

**Comment by ahmadnassri** [comment]
are you guys setting the proper Request Content-Type headers? PHP will not read the request payload or raw body unless the proper headers are set!

**Comment by WanaByte** [comment]
Looking at the interface, no. I had the box checked, but didn't realize that after checking, I still had to specify a Content-Type header since the textbox didn't clear. 

This works a little differently from the 3.x version, where checking the box defaulted to 'application/x-www-form-urlencoded'. Perhaps a little UI hinting by clearing the textbox when you activate the checkbox could make it more clear that 'application/x-www-form-urlencoded' is not actually a value I am sending?

**Comment by evertharmeling** [comment]
KyleWpppd' workaround works for me, It doesn't matter if you set the (Request) Target Content Type for me. 
If it does needs to be set nevertheless, then probably as KyleWpppd suggested it would be better to UI hint it or set a default value.

**Comment by ahmadnassri** [comment]
well the content-type header has to be set to `application/x-www-form-urlencoded` for PHP to read the POST variables, however that's not necessary how the HTTP Spec works, the data can still be sent regardless of the header, so I left it open to the developer to decide.

I could make it automatically default to `application/x-www-form-urlencoded` for sure, and that would help, but I figured it was a well known fact ...

I'll do that for the next release, set a few default header values. as for hinting I added `example:` as a prefix to all those headers, the text in there is a placeholder, it doesnt even stick, the moment you click the field it clears out ... but I guess that's too much of an HTML5 behavior, not many people are used to it.

@evertharmeling can you confirm that setting the header to `application/x-www-form-urlencoded` without the RAW body does the trick for you?

thanks.

**Comment by evertharmeling** [comment]
@ahmadnassri setting the Body > Content Headers > Content-Type to <em>application/x-www-form-urlencoded</em> does indeed the job! 
The thing probably is that developers want things to work out of the box, since 3.0.7 did that ppl expect it worked that standard in the new version. Maybe some hightlighting of fields that are 'mandatory' / 'worth keeping an eye on' could simplify it that, or maybe even a little FAQ, all in all great job!

**Comment by ilbalta** [comment]
Thank you very much!!
I really think a hint could help, not professional (or simply not expert or just very very tired :P) developers would for sure appreciate it.

**Comment by ahmadnassri** [comment]
@evertharmeling yep, I see your point, I was following the W3C specs, its not really required to set the content-type header ... and it doesn't have to be www-form to send a post payload either ... so I was being loose, however next release, I will pre-populate that field since 99% of the cases will be using that ...
