### ISSUE TITLE
OAuth header

### ISSUE THREAD

**Issue by churixho** [ahmadnassri/app-restconsole#53]
The key values pairs in the OAuth header should be comma-separated

**Comment by ahmadnassri** [comment]
you can set the separators in the oAuth dialog ...

**Comment by churixho** [comment]
Ya, I closed this issue after I realized that.

**Comment by dokipen** [comment]
I'm wondering why this is configurable. The RFC clearly states that it should be a comma separator. At the very least it should be set to comma by default. It would have saved me some trouble. :D

http://oauth.net/core/1.0/#auth_header

**Comment by ahmadnassri** [comment]
@dokipen you are correct, the library I initially used for the JavaScript OAuth had space separators by default, and the OAuth server I tested with accepted that with no issues ...

the next release (soon) has a new OAuth library that is up to date with the spec.

**Comment by mrud** [comment]
Would it be possible to change the default from space to comma?
