### ISSUE TITLE
separate values in the Authorization header for Oauth request

### ISSUE THREAD

**Issue by ahmadnassri** [ahmadnassri/app-restconsole#6]
What steps will reproduce the problem?
1. Set target as GET https://api.dropbox.com/0/oauth/request_token (See screenshot)
2. On the Authorization section enter a consumer key
3. On the Authorization section enter a consumer secret
4. Hit 'Send'
5. Response fails with 403. "{"error": "Parameter not found: oauth_consumer_key"}" even though the "oauth_consumer_key" is specified.

What is the expected output? What do you see instead?
See screenshot from my Firefox plugin. The values are "." separated and I am receiving "200 OK" along with the right response in the body.

What version of the product are you using? On what operating system?
Rest console: v3.0.5
Google Chrome version: 12.0.742.68

I've had a quick look at the Oauth 1.0 specification at: http://tools.ietf.org/html/rfc5849 

On page 5 it shows comma separated values in the example header provided there. Hope this helps. Cheers

**Comment by crocodile** [comment]
Still an issue in 3.0.7.

**Comment by ahmadnassri** [comment]
this is fixed in the latest version (4.0.0)
