### ISSUE TITLE
Chrome webstore #resources: links are hyphenated

### ISSUE THREAD

**Issue by jimschubert** [ahmadnassri/app-restconsole#60]
For example:

 ## Resources
- Follow us on Twitter: http://twitter.com/restconsole
- Get the source code: https://github.com/codeinchaos/rest-console
- Report issues: https://github.com/codeinchaos/rest-console/issues
- Donate: https://flattr.com/thing/156628/REST-Console

The github repo is `restconsole`, not `rest-console`. It must have been changed and not updated!

This affects the text in the details and the Support link.

**Comment by ahmadnassri** [comment]
thanks, I renamed the repo just a couple of days ago and had not had the chance to update the links everywhere ...
