### ISSUE TITLE
OAuth base string is wrong

### ISSUE THREAD

**Issue by dokipen** [ahmadnassri/app-restconsole#64]
In SimpleOAuth, when the basestring is created, the URL query string is included in the URI. The spec clearly states the the query string should be omitted from the URI part of the base string. I started down the path to fix this bug, but the SimpleOAuth code is not pretty. You might try trimming the querystring off of the URL before passing it to SimpleOAuth and using the 'parameters' parameter instead.

http://tools.ietf.org/html/rfc5849#section-3.4.1.2

**Comment by ahmadnassri** [comment]
I'm completely dumping SimpleOAuth in favor of this one: http://code.google.com/p/oauth/
SimpleOAuth caused more problems than it helped solve, including the header separator issue.

next release is around the corner, which has the new library and many more improvements.

**Comment by dokipen** [comment]
awesome! I'm glad I didn't spend time fixing it!

**Comment by ahmadnassri** [comment]
yeah, I'm aiming to release end of the month, in the meantime, you're welcome to play with the "dev" branch, just be warned its changing by the hour.
