### ISSUE TITLE
Footer links in tool give 404

### ISSUE THREAD

**Issue by ShawnTuatara** [ahmadnassri/app-restconsole#86]
The "Source Code" and "Issues" link on the footer have https://github.com/codeinchaos/rest-console but the project is actually without the hyphen in the middle.

**Comment by ahmadnassri** [comment]
@ShawnTuatara new version in the works (a bit of a rewrite) will take care of this.

thanks!

**Comment by pv7721** [comment]
The issue is still there!

**Comment by ShawnTuatara** [comment]
I see this as resolved. If you go to: https://github.com/codeinchaos/restconsole it does show the correct links at the bottom. The link I provided above will always fail as it is a bad link.
