### ISSUE TITLE
Problem with signature generated for SHA1

### ISSUE THREAD

**Issue by jdxpointe1** [ahmadnassri/app-restconsole#90]
When setting the Oauth authentication header values the HMAC-SHA1 signature generated is not matching. We have tried verifying against all available sources for generating SHA1 signatures and the Rest Console is not matching any of them but all the other sources do match each other and the servers signature generated through HMAC-SHA1 to verify.

**Comment by jdxpointe1** [comment]
Correction: Checked the parameters processed and the signature produced by the server and found that Rest Console was correct and server parameters were processed incorrectly for producing the signature. The parameters being provided for the other sites to compare included the incorrect values as well which led to the inconsistency...

**Comment by ahmadnassri** [comment]
awesome, glad to hear REST Console was correct... a tool I've always used in validating oAuth signature conflicts without fail: the Netflix Oauth Test: http://developer.netflix.com/resources/OAuthTest

I even used it when building REST Console ... the same libraries are built in and are what's used to generate the signatures
